### ISSUE TITLE
Thanks for the package!

### ISSUE THREAD

**Issue by Edouard-Legoupil** [corybrunson/ggalluvial#106]
Not an issue - but a thanks! - 

Building on the example of your package - I just inserted a standard plotting function within our unhcrdatapackage - 
[plot_ctr_origin_history](https://edouard-legoupil.github.io/unhcrdatapackage/reference/plot_ctr_origin_history.html) 

Thanks for the contribution

**Comment by corybrunson** [comment]
Very cool! Thank you, and i'm glad it has come in so handy. Thanks should also go to @mbojan for inspiring (and providing the data for) that example, as well as for the extension as a whole.

**Comment by mbojan** [comment]
@Edouard-Legoupil @corybrunson 

Thanks! The function used for the original refugee figure in [**alluvial**](https://github.com/mbojan/alluvial/blob/master/README.md) was in fact designed and implemented by @geotheory. My inspiration in turn came from my admiration of the figures in [Rosvall & Bergstrom](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2811724/) and the urge to be able to create similar visualizations myself in R.
