### ISSUE TITLE
Computation failed in `stat_stratum()`.

### ISSUE THREAD

**Issue by DrZhangjilin** [corybrunson/ggalluvial#109]
### When trying to make alluvial plots, I always get the following error:

```
Warning message:
Computation failed in `stat_stratum()`
Caused by error in `default_missing()`:
! could not find function "default_missing"
```
This issue did not occur in previous versions.
I used the example code in the help documentation.

```
gg <- ggplot(data = refugees_sub,
             aes(x = year, y = refugees, alluvium = country)) +
  theme_bw() +
  scale_fill_brewer(type = "qual", palette = "Set3")
# proportional knot positioning (default)
gg +
  geom_alluvium(aes(fill = country),
                alpha = .75, decreasing = FALSE, width = 1/2) +
  geom_stratum(aes(stratum = country), decreasing = FALSE, width = 1/2)
# constant knot positioning
```
Is there something I am doing wrong or a way I can fix this?

**Comment by corybrunson** [comment]
Hi @DrZhangjilin, please see #107 and #108.

**Comment by DrZhangjilin** [comment]
Thank you very much for your timely reply!

I referred to the solution of #107  and installed the developer version of ggalluvial, then the problem was solved!

**Comment by corybrunson** [comment]
Excellent. : )
