### ISSUE TITLE
Add labels on the right of alluvial plot

### ISSUE THREAD

**Issue by zhangguoqianggu** [corybrunson/ggalluvial#114]
Hi, I would like to ask if it would be possible to add labels on the right of the alluvial plot, as below:

<img width="1111" alt="image" src="https://github.com/corybrunson/ggalluvial/assets/64090640/c717c52c-9c37-40f8-8a03-c21532f7be6f">

https://r-graph-gallery.com/web-line-chart-with-labels-at-end-of-line.html

I tried to use geom_text_repel(), but probably the code I wrote was wrong.

library(ggalluvial)
titanic_wide <- data.frame(Titanic)

ggplot(
  data = titanic_wide,
  aes(axis1 = Class, axis2 = Sex, axis3 = Age, y = Freq)
) +
  scale_x_discrete(limits = c("Class", "Sex", "Age"), expand = c(.2, .05)) +
  xlab("Demographic") +
  geom_alluvium(aes(fill=Class)) +
  geom_stratum(aes(fill=Class)) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)) ) +
  theme_minimal() +
  ggtitle(
    "passengers on the maiden voyage of the Titanic",
    "stratified by demographics and survival"
  )+
  scale_fill_manual(
    values=c("red","orange","green","blue"),
    breaks=c("1st","2nd","3rd","Crew"),
    labels=c("1st","2nd","3rd","Crew"),
    na.value = NA
  ) +
  geom_text_repel(
    aes(color = Class, label = Freq) )

**Comment by corybrunson** [comment]
Hi @zhangguoqianggu, thanks for noting this. I should probably explicitly state on the labeling vignette that the data must be in lodes form for either solution to work. That requires making some changes to the structure of the `ggplot()` layers and aesthetics, but also it requires familiarity with another trick: creating a new variable for the labels that only takes values on the rightmost axis. So this can't be done automatically at present; the user must tell the plot which alluvia or strata get labels. Maybe this behavior could be made into a convenient feature, but i haven't had time to develop the package much in the last year and might not for another still.

Here is a plot based on your code above. Maybe it's not exactly what you want, but it should get you started.

``` r
library(ggalluvial)
#> Loading required package: ggplot2
library(ggrepel)
titanic_wide <- data.frame(Titanic)
titanic_long <- to_lodes_form(titanic_wide, axes = 1:4,
                              key = "variable", value = "value", id = "cohort",
                              diffuse = Class)

ggplot(
  data = titanic_long,
  aes(x = variable, stratum = value, alluvium = cohort, y = Freq)
) +
  geom_alluvium(aes(fill=Class)) +
  geom_stratum(aes(fill=Class)) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)) ) +
  theme_minimal() +
  ggtitle(
    "passengers on the maiden voyage of the Titanic",
    "stratified by demographics and survival"
  )+
  scale_fill_manual(
    values=c("red","orange","green","blue"),
    breaks=c("1st","2nd","3rd","Crew"),
    labels=c("1st","2nd","3rd","Crew"),
    na.value = NA,
    aesthetics = c("fill", "color")
  ) +
  geom_text_repel(stat = "alluvium",
    aes(color = Class,
        label = ifelse(variable == "Survived" & Freq >= 10, Freq, NA)),
    direction = "y", nudge_x = .5)
#> Warning: Removed 108 rows containing missing values (`geom_text_repel()`).
```

![](https://i.imgur.com/7uiyl4I.png)

<sup>Created on 2023-06-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by zhangguoqianggu** [comment]
Thank you so much for your help! This looks cool! 😄

**Comment by corybrunson** [comment]
Great, thanks for confirming!

**Comment by Yingjie4Science** [comment]
Hi @corybrunson I have a similar but slightly different question: in your last example here [http://corybrunson.github.io/ggalluvial/reference/geom_flow.html], is it possible to only show the labels on the last axis, i.e., "ms460_NSA". 

I have tried `label = ifelse(survey == "ms460_NSA" & after_stat(n)>10, after_stat(n), NA))`, but with an error "object 'survey' not found"
