### ISSUE TITLE
reverse Parameter Purpose Mystery

### ISSUE THREAD

**Issue by DarioS** [corybrunson/ggalluvial#123]
In the vignette, I see `reverse = FALSE`. But, it is not a parameter of `geom_alluvium` nor `layer` (which accepts `...`)

> `...` Additional arguments passed to `ggplot2::layer()`.

**Comment by corybrunson** [comment]
It is a parameter of the `stat_*()` layers, not the `geom_*()` layers. : )

(Parameters to either layer can be passed to the other layer; they are reconciled in `layer()`.)

**Comment by corybrunson** [comment]
Presumed resolved but please reopen if not!
