### ISSUE TITLE
Add example figure to README?

### ISSUE THREAD

**Issue by BarkleyBG** [corybrunson/ggalluvial#15]
Hi there, I'm recommending a friend take a look at this package. I think the GH repo would be improved if you added an example figure to the README and/or to http://corybrunson.github.io/ggalluvial/. 

(I like the example figure at http://corybrunson.github.io/ggalluvial/articles/ggalluvial.html, but I'm suggesting that you "bring that forward" by adding it to the README).

This is great work!

**Comment by corybrunson** [comment]
Thank you for saying so! I'm glad you find it useful.

I did this originally, and the README evolved into the vignette. But the remaining README does fill a bit bare. I'll put this on the agenda for the next release. (The website landing page is generated directly from the README, so one swoop will fell both issues.)
