### ISSUE TITLE
write a new vignette about how flows are ordered within strata

### ISSUE THREAD

**Issue by corybrunson** [corybrunson/ggalluvial#36]
A lot of functionality goes into this determination, and most of it in most use cases is obscured from the user. See the exposition in [this SO answer](https://stackoverflow.com/a/57233002/4556798).

**Comment by RubieLu** [comment]
I am wondering if ggalluvial can remain the natural order of the rows within strata. 
I have tried `aes.bind = TRUE`, but the result was not what I expected. 
Since the order of my dataset is meaningful, is it possible to plot without intersecting the strata at lodes?
