### ISSUE TITLE
Question: geom_alluvim vs geom_flow

### ISSUE THREAD

**Issue by akarlinsky** [corybrunson/ggalluvial#38]
Kind of a silly question - but what is the difference between geom_flow and geom_alluvium?

**Comment by corybrunson** [comment]
The difference is discussed in [the technical introduction](http://corybrunson.github.io/ggalluvial/articles/ggalluvial.html). You can also check the documentation of the functions [here](http://corybrunson.github.io/ggalluvial/reference/geom_alluvium.html) and [here](http://corybrunson.github.io/ggalluvial/reference/geom_flow.html), which briefly describe both geoms. If anything's still unclear, or if your question is more specific, let me know and i'll try to clarify!

**Comment by corybrunson** [comment]
Closing this issue to clear the queue, but can reopen (and regardless will still respond) if the underlying issue has not been resolved.
