### ISSUE TITLE
Import plyr

### ISSUE THREAD

**Issue by thomasp85** [corybrunson/ggalluvial#49]
The new version of ggplot2 no longer depend on plyr. ggalluvial has somehow been able to have `plyr::` calls in its code without explicitly depending on plyr, but these will now break as plyr is no longer present on a clean system.

To fix this, add plyr to Imports in the DESCRIPTION file and submit to CRAN

**Comment by corybrunson** [comment]
Thank you! I believe i've resolved this, but i'll leave the issue open until i've submitted the next version to CRAN. (I'm holding off on that until a JOSS review is completed, which will be shortly.)

**Comment by ShixiangWang** [comment]
@corybrunson Could fix it to CRAN ASAP. I got an email to remind the archive of this package and also its reverse dependencies.

![image](https://user-images.githubusercontent.com/25057508/79404788-40c29400-7fc5-11ea-9738-94a2500c7868.png)

**Comment by corybrunson** [comment]
Thanks for the prompt. I submitted the patch several weeks ago but forgot to follow through with the link-clicking email. It's done.

**Comment by corybrunson** [comment]
Fixed with v0.11.3, now on CRAN.
