### ISSUE TITLE
Links to documentation 404 error

### ISSUE THREAD

**Issue by jasonpott** [corybrunson/ggalluvial#60]
### Description of the issue
Links pointing to http://corybrunson.github.io/ggalluvial/ in repo and on search engines are returning 404 error.

I was hoping to look at the documentation for the package but I was unable to see them in the repo I believe they are at on the GitHub page linked above. 

Thank you for your time and efforts on this package it has been incredibly useful.

**Comment by corybrunson** [comment]
Thank you so much! I recently changed the default branch from `master` to `main` but "assumed" it would automatically update the website build source (actually i just didn't think to check). It's fixed now, simply by having restored `master` as a copy of `cran`. I'll update the README to clarify this.
