### ISSUE TITLE
Updates to vignette

### ISSUE THREAD

**Issue by qdread** [corybrunson/ggalluvial#74]
Hi Cory, I started this issue to work on the updates to the Shiny/ggalluvial vignette that we talked about back in November on #69 . I am starting it in the [vignette-updates branch on my fork](https://github.com/qdread/ggalluvial/tree/vignette-updates).

So far I have solved the problem of unequal `size` of each row which was pretty easy.

To-do list:

- [x] Deal with unequal widths of alluvia
- [x] Make an app for both wide and long alluvial data
- [x] Replace fake data with real-world data
- [x] Embed the Shiny app itself in the vignette
- [x] Update content of vignette to reflect changes

I'll update you with any progress!

**Comment by corybrunson** [comment]
@qdread great, thank you—i'll watch out for updates and be ready to help if...helpful.

Would you mind converting your bulleted list to a checkbox list? If more things turn out to be appropriate for the next version, then they can be added, as well as accomplished tasks marked as done.

**Comment by qdread** [comment]
I am making good progress on this. The branch has half a dozen commits on it and will have a few more before it's done. I was wondering what is your preference: keep all the commits "as is" or rebase them so there are fewer commits cluttering up your history if the PR gets merged?

**Comment by corybrunson** [comment]
@qdread i'm not too concerned with the proliferation of commits! But i also never learned to rebase, so i would lean against it even if i were. (My major problem is doing too much in one commit.)
