### ISSUE TITLE
Plotting summarized data

### ISSUE THREAD

**Issue by pshmell** [corybrunson/ggalluvial#83]
Hi, I am having some trouble and am unsure if I am using the package incorrectly or if ggalluvial is not designed to plot data that has already been summarized. I have a large dataframe which I have summarized to produce what I would like a simple alluvial chart of, reproduced below:

CB_Group  PCT    TYPE                       
  <fct>    <dbl> <chr>                      
0-30%    0.513     Current (no new benefit)   
0-30%    0.610     With Monthly Benefit ($500)
0-30%    0.573    With Rent Reduction (25%)  
30-50%   0.236   Current (no new benefit)   
30-50%   0.219   With Monthly Benefit ($500)
30-50%   0.208   With Rent Reduction (25%)  
50-100%  0.251   Current (no new benefit)   
50-100%  0.171    With Monthly Benefit ($500)
50-100%  0.218   With Rent Reduction (25%) 

I would like the TYPE to be on the x-axis, the PCT to be on the y-axis, and the CB_Group to be the fill color. I have produced summary tables in this way because this dataset is weighted, and doing weighting within ggplot seems inadvisable.

I either get an empty plot or an error telling me that I have not supplied the full set of parameters (e.g. "Error in get_alluvial_type(data) :   Parameters `x`, `stratum`, and `alluvium` are required for data in lodes form."). However, I can't supply additional parameter as I only have three columns in my summary table.

Thanks. Nice package, just can't seem to get it to produce this plot for me, would like to know if I am using it incorrectly or if it is not designed to do this.

Paul

**Comment by corybrunson** [comment]
Hi @pshmell and thanks for asking. I think the best explanation is, as you guessed, that these data are already summarized. Specifically, you have the percentage CB_Group breakdown at each TYPE, but not which (or what percentage of) cases have each 3-value profile. See the fourth and fifth examples in [the primary vignette](http://corybrunson.github.io/ggalluvial/articles/ggalluvial.html), where this is accomplished in lodes form using the identifier columns `student` and `subject`, respectively. But please check back if that doesn't resolve your question!

**Comment by corybrunson** [comment]
Assuming resolved, but feel free to reopen if not. : )
