### ISSUE TITLE
The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.

### ISSUE THREAD

**Issue by dcarbajo** [corybrunson/ggalluvial#93]
Hello! Been using `ggalluvial` for a while with success, but recently, every time I use it I get the following warning:

```
Warning message:
The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
```

I am afraid this becomes a problem in the near future... Is there a way to circumvent this?

I can make a MWE if you need, but I notice this warning already appears on your vignette here (`Lodes (long) format` section): https://corybrunson.github.io/ggalluvial/articles/ggalluvial.html

Can this warning be fixed? Many thanks!

![Screenshot 2021-10-15 at 4 54 51 PM](https://user-images.githubusercontent.com/54791796/137480359-7af26585-7d11-41b7-b13a-f5d5f6e44548.png)

**Comment by corybrunson** [comment]
@dcarbajo thank you for pointing this out. I simply haven't been paying attention. I'll take a look very soon.

**Comment by dcarbajo** [comment]
Hi @corybrunson many thanks for looking into this! any news on this front? thanks again

**Comment by corybrunson** [comment]
Hi @dcarbajo you're welcome—in advance, since i haven't put out the new release yet. Were you able to run the new code using your data? Did any warnings appear?

**Comment by dcarbajo** [comment]
Hi @corybrunson I'm realizing I never updated you on this. I didn't show that warning anymore installing from `main`. However, I think since I upgraded to R 4.2.0, I encounter this other warning, if you want to have a look!

```
Warning message:
`spread_()` was deprecated in tidyr 1.2.0.
Please use `spread()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```

Should I open a separate issue for this? Many thanks again!

**Comment by corybrunson** [comment]
@dcarbajo yes, please! Thanks for pointing this out.
