### ISSUE TITLE
Some inspiration for new/alternative layouts

### ISSUE THREAD

**Issue by mbojan** [corybrunson/ggalluvial#96]
Just came across https://github.com/oxinabox/LayeredLayouts.jl which seems an interesting inspiration for possible alternative layouts for the boxes and alluvia.

**Comment by corybrunson** [comment]
Oh, this makes me feel guilty for having ignored #79 for so long, and i won't have time to engage with it properly for a while still. Good point of reference, thank you!

**Comment by corybrunson** [comment]
Linking from [this older issue](https://github.com/corybrunson/ggalluvial/issues/6) and closing to reduce clutter.
